apiVersion: batch/v1
kind: CronJob
metadata:
  name: springboot-email-cron-10m
  namespace: springboot
spec:
  schedule: "*/10 * * * *"  # Every 10 minutes
  concurrencyPolicy: Allow  # Allow new jobs to run even if the previous one is not completed
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: springboot-email-10m
              image: kubernetspoccron.azurecr.io/springboot-argo:bwWouJ-e505
              args:
                - "curl"
                - "http://72.152.40.37/users/cronten"  # Replace with your Spring Boot service endpoint
              imagePullPolicy: Always

---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: springboot-email-cron-5m
  namespace: springboot
spec:
  schedule: "*/5 * * * *"  # Every 5 minutes
  concurrencyPolicy: Allow  # Allow new jobs to run even if the previous one is not completed
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: springboot-email-5m
              image: kubernetspoccron.azurecr.io/springboot-argo:bwWouJ-e505
              args:
                - "curl"
                - "http://72.152.40.37/users/cronfive"  # Replace with your Spring Boot service endpoint
              imagePullPolicy: Always
