apiVersion: batch/v1
kind: CronJob
metadata:
  name: springboot-email-cron-10m
  namespace: springboot
spec:
  schedule: "*/10 * * * *"  # Every 10 minutes
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: springboot-email-10m
              image: kubernetspoccron.azurecr.io/springboot-argo:hSo1hi-4132
              args:
                - "curl"
                - "http://72.152.40.37/users/cronten"  # Replace with your Spring Boot service endpoint
              imagePullPolicy: Always
              env:
                - name: SPRING_DATASOURCE_URL
                  value: "jdbc:mysql://mysql-service:3306/apulapa"
                - name: SPRING_DATASOURCE_USERNAME
                  valueFrom:
                    secretKeyRef:
                      name: mysql-secret
                      key: DB_USER
                - name: SPRING_DATASOURCE_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: mysql-secret
                      key: DB_PASSWORD
          restartPolicy: OnFailure

---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: springboot-email-cron-5m
  namespace: springboot
spec:
  schedule: "*/5 * * * *"  # Every 5 minutes
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: springboot-email-5m
              image: kubernetspoccron.azurecr.io/springboot-argo:hSo1hi-4132
              args:
                - "curl"
                - "http://72.152.40.37/users/cronfive"  # Replace with your Spring Boot service endpoint
              imagePullPolicy: Always
              env:
                - name: SPRING_DATASOURCE_URL
                  value: "jdbc:mysql://mysql-service:3306/apulapa"
                - name: SPRING_DATASOURCE_USERNAME
                  valueFrom:
                    secretKeyRef:
                      name: mysql-secret
                      key: DB_USER
                - name: SPRING_DATASOURCE_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: mysql-secret
                      key: DB_PASSWORD
          restartPolicy: OnFailure
